### ISSUE TITLE
Fails to build on Ubuntu 11.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rampageX/firmware-mod-kit#40]
```
What steps will reproduce the problem?
1. Attempt to build firmware-mod-kit on xubuntu 11.10


What is the expected output? What do you see instead?
/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squashf
s-3.2-r2-lzma//C/Compress/Lzma/libunlzma.a(uncomp.o): In function `sqlzma_un':
uncomp.c:(.text+0x66): undefined reference to `inflateReset'
uncomp.c:(.text+0xa7): undefined reference to `inflate'
uncomp.c:(.text+0x253): undefined reference to `zError'
/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squashf
s-3.2-r2-lzma//C/Compress/Lzma/libunlzma.a(uncomp.o): In function `sqlzma_init':
uncomp.c:(.text+0x430): undefined reference to `inflateInit_'
collect2: ld returned 1 exit status
make[3]: *** [unsquashfs] Error 1
make[3]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squash
fs-3.2-r2-lzma/squashfs3.2-r2/squashfs-tools'
make[2]: *** [all] Error 2
make[2]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squash
fs-3.2-r2-lzma'
make[1]: *** [all] Error 2
make[1]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others'
make: *** [all] Error 2

This is the second error, the first one was fixed by switching out cramfsswap 
with a version referenced by: 
https://bugs.launchpad.net/ubuntu/+source/cramfsswap/+bug/770935

And I have no idea how to fix this one. 

What version of the product are you using? On what operating system?
SVN checkout from November 1, 2011

Please provide any additional information below.

I successfully built it on Ubuntu 10.04 without problem. 


```

Original issue reported on code.google.com by `Sunrunne...@gmail.com` on 2 Nov 2011 at 1:45
