### ISSUE TITLE
Compile error in Arch x64

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rampageX/firmware-mod-kit#55]
```
Compile in Arch x64 with glibc 2.15-7

/usr/bin/ld: mksquashfs.o: undefined reference to symbol 'log10@@GLIBC_2.2.5'
/usr/bin/ld: note: 'log10@@GLIBC_2.2.5' is defined in DSO /lib/libm.so.6 so try 
adding it to the linker command line
/lib/libm.so.6: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[3]: *** [mksquashfs] Error 1
make[3]: Leaving directory 
`/home/arch/Desktop/trunk/src/others/squashfs-3.3-grml-lzma/squashfs3.3/squashfs
-tools'
make[2]: *** [all] Error 2
```

Original issue reported on code.google.com by `carbonjiao` on 7 Mar 2012 at 2:06
